[package]
name = "program-change"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
nih_plug = { git = "https://github.com/robbert-vdh/nih-plug.git", commit="756d5a33158b35e7743fa11c030baa29764a4f95" }

